import {requireSupabase} from '../lib/supabase';
import type {CertificateTemplate} from '../types';
export async function getActiveTemplate(){const {data,error}=await requireSupabase().from('certificate_templates').select('*').eq('is_active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data as CertificateTemplate|null;}
export async function listTemplates(){const {data,error}=await requireSupabase().from('certificate_templates').select('*').order('created_at',{ascending:false});if(error)throw error;return (data??[]) as CertificateTemplate[];}
export async function updateTemplate(id:string,values:Partial<CertificateTemplate>){const {data,error}=await requireSupabase().from('certificate_templates').update(values).eq('id',id).select().single();if(error)throw error;return data as CertificateTemplate;}
export async function uploadTemplate(file:File,name:string){const sb=requireSupabase();if(!/^image\/(png|jpeg|jpg)$/.test(file.type))throw new Error('Only PNG and JPG templates are supported in the browser editor.');if(file.size>10*1024*1024)throw new Error('Template must be 10 MB or smaller.');const path=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('certificate-templates').upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;const {data:pub}=sb.storage.from('certificate-templates').getPublicUrl(path);const img=await createImageBitmap(file);const {data,error}=await sb.from('certificate_templates').insert({template_name:name,template_file_url:pub.publicUrl,template_width:img.width,template_height:img.height,name_x:img.width*.25,name_y:img.height*.42,name_width:img.width*.5,name_height:img.height*.12,font_family:'Arial',font_size:72,font_weight:600,text_alignment:'center',text_color:'#111827',letter_spacing:0,line_height:1.1,allow_multiline:false,min_font_size:24,is_active:false}).select().single();if(error)throw error;return data as CertificateTemplate;}
export async function activateTemplate(id:string){const sb=requireSupabase();const {error:e1}=await sb.from('certificate_templates').update({is_active:false}).neq('id',id);if(e1)throw e1;const {data,error}=await sb.from('certificate_templates').update({is_active:true}).eq('id',id).select().single();if(error)throw error;return data as CertificateTemplate;}

export async function uploadFont(templateId:string,file:File){if(file.size>5*1024*1024)throw new Error('Font must be 5 MB or smaller.');if(!/font\/(ttf|otf)|application\/font|application\/x-font-ttf|application\/x-font-opentype/.test(file.type) && !/\.(ttf|otf)$/i.test(file.name))throw new Error('Upload a TTF or OTF font.');const sb=requireSupabase();const path=`fonts/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('certificate-templates').upload(path,file,{upsert:false});if(up.error)throw up.error;const {data:pub}=sb.storage.from('certificate-templates').getPublicUrl(path);return updateTemplate(templateId,{font_file_url:pub.publicUrl,font_family:file.name.replace(/\.(ttf|otf)$/i,'')});}
