import {useEffect,useState} from 'react';
import {Activity,Download,FileCheck,Files,MessageSquare,ShieldCheck,TrendingUp,RefreshCw} from 'lucide-react';
import {Card,Button} from '../components/ui';
import {dashboardStats,recentDownloads} from '../services/analytics';
import {formatDate} from '../lib/utils';
import {requireSupabase} from '../lib/supabase';

export default function AdminDashboard(){
 const [s,setS]=useState<any>(null); const [activity,setActivity]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [stats,rows]=await Promise.all([dashboardStats(),recentDownloads(10)]);setS(stats);setActivity(rows)}finally{setLoading(false)}};
 useEffect(()=>{load().catch(()=>{});const sb=requireSupabase();const ch=sb.channel('download-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'certificate_downloads'},()=>{load().catch(()=>{})}).subscribe();return()=>{sb.removeChannel(ch)}},[]);
 const cards=s?[['Live certificates',s.live_certificates,Files,'Currently active certificates'],['Total downloads',s.total_downloads,Download,'All successful downloads'],['Downloads today',s.downloads_today,TrendingUp,'Since midnight'],['Downloads this month',s.downloads_month,FileCheck,'Current month'],['Unique downloaded',s.unique_downloaded_certificates,ShieldCheck,'Certificates downloaded at least once'],['Feedback',s.feedback_total,MessageSquare,`${s.feedback_unread} unread`]]:[];
 return <div><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-semibold uppercase tracking-widest text-slate-400">Operations center</div><h1 className="mt-1 text-2xl font-bold">Dashboard</h1><p className="mt-1 text-sm text-slate-400">A live view of certificates, downloads and public feedback.</p></div><Button variant="secondary" onClick={()=>load().catch(()=>{})}><RefreshCw size={15}/> Refresh</Button></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([l,v,I,sub]:any)=><Card key={l} className="p-5"><div className="flex items-center justify-between"><span className="text-sm font-medium text-slate-400">{l}</span><I size={18} className="text-slate-400"/></div><div className="mt-3 text-3xl font-bold">{loading?'—':v}</div><div className="mt-1 text-xs text-slate-400">{sub}</div></Card>)}</div>
 <Card className="mt-6 overflow-hidden"><div className="flex items-center gap-3 border-b border-white/10 p-5"><div className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-400/10 text-emerald-300"><Activity size={18}/></div><div><h2 className="font-semibold">Live download activity</h2><p className="text-xs text-slate-400">Updates automatically when a certificate is downloaded.</p></div><span className="ml-auto inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400/100"/> Live</span></div><div className="divide-y divide-white/10">{activity.length?activity.map((x,i)=><div key={x.id??i} className="flex items-center justify-between gap-3 p-4"><div><div className="text-sm font-medium">{x.certificates?.recipient_name??'Certificate'} downloaded a certificate</div><div className="text-xs text-slate-400">{x.certificates?.certificate_id??''} · {x.device_type??'Unknown device'} · {x.browser??'Unknown browser'}</div></div><span className="whitespace-nowrap text-xs text-slate-400">{formatDate(x.downloaded_at)}</span></div>):<div className="p-8 text-center text-sm text-slate-400">No download activity yet.</div>}</div></Card></div>
}
